################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

[en.params]
home = "Home"
# footer content
footer_content = "Morocco-based clean-energy and industrial platform focused on building, owning, and operating real assets across the renewable-energy value chain.<br><br> The group operates across five complementary verticals: utility-scale solar power generation, solar panel manufacturing, advanced materials (polysilicon), solar services and maintenance, and clean-energy mobility solutions. "
copyright = "Copyright © GPM Holding, 2025 All rights reserved"


################################### French language #####################################
[fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2

[fr.params]
home = "Accueil"
# footer content
footer_content = "GPM Holding - is a pioneer venture at the forefront of sustainable energy, currently operating in 3 segments of the renewable energy sector: PV Solar Panels manufacturing, PV Solar Parks and Operation & Maintenance of PV Solar Parks to revolutionizing the renewable energy sector in Africa. Our mission is to continue to play an important role in supporting African countries’ ongoing global renewable energy development for the benefit of everyone. "
# copyright
copyright = "Copyright © GPM Holding, 2025 All rights reserved"
