############# French navigation ##############
# main menu
[[main]]
name = "Accueil"
url = "/"
weight = 1

[[main]]
name = "À propos"
url = "#about"
weight = 2

#[[main]]
#name = "GPM Services"
#url = "service/"
#weight = 6

#[[main]]
#name = "GPM Mobility"
#url = "service/"
#weight = 7

#[[main]]
#name = "Blog"
#url = "blog/"
#weight = 4

#[[main]]
#name = "Team"
#url = "team/"
#weight = 6

[[main]]
weight = 3
name = "Nos Entités"
url = "project/"
hasChildren = true

  [[main]]
  parent = "Nos Entités"
  name = "GPM Parks"
  url = "project/gpm-parks"
  weight = 1

  [[main]]
  parent = "Nos Entités"
  name = "Solaris"
  url = "project/solaristangier"
  weight = 2

  [[main]]
  parent = "Nos Entités"
  name = "Polysilicium"
  url = "project/sondiale/"
  weight = 3

  [[main]]
  parent = "Nos Entités"
  name = "GPM Services"
  url = "project/gpm-services/"
  weight = 4

  [[main]]
  parent = "Nos Entités"
  name = "GPM Mobility"
  url = "project/gpm-mobility/"
  weight = 5

[[main]]
name = "Contact"
url = "#contacts"
weight = 4

# footer menu
[[footer_menu]]
name = "GPM Parks"
url = "project/gpm-parks"
weight = 1

[[footer_menu]]
name = "Solaris"
url = "project/solaristangier"
weight = 2

[[footer_menu]]
name = "Polysilicium"
url = "project/sondiale/"
weight = 3

[[footer_menu]]
name = "GPM Services"
url = "project/gpm-services/"
weight = 4

[[footer_menu]]
name = "GPM Mobility"
url = "project/gpm-mobility/"
weight = 5

# footer bottom links
[[footer]]
name = "Conditions d'utilisation"
url = "terms/"
weight = 1

#[[footer]]
#name = "Politique de confidentialité"
#url = "privacy-policy/"
#weight = 2

